server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/booard
    username: root
    password: test1234

  jpa:
      database: mysql
      database-platform: org.hibernate.dialect.MariaDBDialect
      generate-ddl: true
      hibernate:
        ddl-auto: create
      show_sql: true

jwt:
  secret_key: YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5

    #  인코딩된 문자 32자 이상 필요.(특수문자)
    #  beyondaccesstokensecretkeybeyondaccesstokensecretkeybeyondaccesstokensecretkey